version: '3'

services:
  runner:
    build: .
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    environment:
      - ORGANIZATION=YOU_USERNAME/REPO
      - ACCESS_TOKEN=TOKEN_FOUND_IN_RUNNERS_PAGE
