version: '3'

services:
  runner:
    image: rhennancordeiro/github-actions:latest
    environment:
      - ORGANIZATION=RhennanCordeiro
      - ACCESS_TOKEN=
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /home/docker/container-data:/home/docker/container-data:rw
