version: '3'

services:
  runner:
    build: .
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    environment:
      - ORGANIZATION=RhennanCordeiro/
      - ACCESS_TOKEN=

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /home/container-storage:/home/container-storage:rw
